### ISSUE TITLE
Record/display statistics from study mode

### ISSUE THREAD

**Issue by GoodChessMind** [jven/studyopenings#13]
Similar to what chess position trainer already has, have a percentage meter next to the opening to show a percentage of how much of the opening you memorized.

**Comment by jven** [comment]
More generally, some information will have to be recorded from study mode and displayed to the user in build mode (or perhaps some new mode).

**Comment by jven** [comment]
43d820715d4ead2de453ad2339298940dd66430e

I've added a new "Evaluate" mode which shows statistics about how well you're studying the lines/positions in a given repertoire. Here's a screenshot:

<img width="1189" alt="screen shot 2019-02-01 at 1 18 11 am" src="https://user-images.githubusercontent.com/1039300/52106095-6bdae680-25bf-11e9-9226-17200a0cc228.png">
