### ISSUE TITLE
Allow reverting how scrolling works

### ISSUE THREAD

**Issue by rizka10** [jven/studyopenings#26]
I'm annoyed by how scrolling works oppositely to how it works on Lichess for instance. If you scroll down there you move forward, down the moves list. Maybe change that altogether to match common practice, or add a little user preferences section to allow user to decide? (I love the site btw!)

**Comment by jven** [comment]
Oops, thanks for filing this. I reversed the direction in b8fed7504a97db5644d788d4aef5c2d4a1f4ab76, it should be fixed in the live site now. Glad to hear you love the site!

**Comment by rizka10** [comment]
Thank you! :+1: I couldn't help my habits and kept going to wrong direction all the time. 😛
